# Generated by Django 2.2.9 on 2020-01-22 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20200113_0605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'Student_details'},
        ),
    ]
