# Generated by Django 2.2.9 on 2020-01-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_auto_20200123_0627'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('photo', models.FileField(upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'User',
            },
        ),
        migrations.RemoveField(
            model_name='registration',
            name='address',
        ),
    ]
